<DrinkImage@ILeftBody+Image>:
    source: ""
    allow_stretch: True
    keep_ratio: False

<Drink>:
    dialog: None # Reference to the dialog box
    item_screen: None # Reference to the item screen for this entree
    source: ""
    on_release:
        self.dialog.dismiss()
        self.item_screen.drink = self.text
        self.item_screen.drink_cost = self.cost
        toast("Chose " + self.text)
    DrinkImage:
        source: root.source
